include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat these as warnings instead of errors
    deprecated_member_use: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Disable info-level rules that create noise
    avoid_print: false  # Allow print during development (replace with logger later)
    use_super_parameters: false  # Style preference, not critical
    prefer_final_fields: false  # Style preference
    constant_identifier_names: false  # Allow SCREAMING_SNAKE_CASE constants
    non_constant_identifier_names: false  # Allow snake_case for DB fields
    unnecessary_brace_in_string_interps: false  # Style preference
    unnecessary_string_interpolations: false  # Style preference
    curly_braces_in_flow_control_structures: false  # Style preference
    unnecessary_import: false  # Can cause issues when refactoring
    empty_catches: false  # Sometimes needed for silent error handling
    sized_box_for_whitespace: false  # Style preference
    unnecessary_to_list_in_spreads: false  # Style preference
    file_names: false  # Allow special characters in filenames
    no_leading_underscores_for_local_identifiers: false  # Style preference